config/routes.rb
MyTimeline::Engine.routes.draw do
  get 'health_graph/scrape' => 'health_graph#scrape', as: "health_graph_scrape"
  resources :health_graph
end

app/models/my_timeline/health_graph/cardio_activity.rb
module MyTimeline
  module HealthGraph
    class CardioActivity < ActiveRecord::Base
      self.table_name = :my_timeline_health_graph_cardio_activities
      belongs_to :event, dependent: :destroy

      attr_protected unless rails4?

      def self.keep_original_time_zone?
        true
      end
    end
  end
end

app/controllers/my_timeline/health_graph_controller.rb
module MyTimeline
  class HealthGraphController < MyTimeline::ApplicationController

    def new
      ::HealthGraph.configure do |config|
        config.client_id                  = MyTimeline::HealthGraph.client_id
        config.client_secret              = MyTimeline::HealthGraph.client_secret
        config.authorization_redirect_url = "#{root_url}/health_graph/code"
      end

      redirect_to ::HealthGraph.authorize_url
    end

    def show
      access_token = ::HealthGraph.access_token(params[:code])

      @user.settings(:health_graph).user_token = access_token
      @user.save!
      redirect_to control_panel_path, notice: "Connection Successful!"
    end

    def scrape
      scrape_status = MyTimeline::HealthGraph::HealthGraphScraper.new(@user).scrape
      redirect_to :back, notice: scrape_status
    end
  end
end

app/views/my_timeline/health_graph/_control_panel.html.erb
<h3> Health Graph Settings </h3>
<% if @user.settings(:health_graph).user_token %>
  <%= button_to "Scrape runs!", health_graph_scrape_path, method: :get, class: "btn btn-primary" %>
<% else %>
  <%= button_to "Connect to Runkeeper", new_health_graph_path, method: :get, class: "btn btn-primary" %>
<% end %>